// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/refined-a.tsx": () => import("../components/mockups/refined-a.tsx"),
  "./components/mockups/refined-b.tsx": () => import("../components/mockups/refined-b.tsx"),
  "./components/mockups/variant-a.tsx": () => import("../components/mockups/variant-a.tsx"),
  "./components/mockups/variant-b.tsx": () => import("../components/mockups/variant-b.tsx"),
  "./components/mockups/variant-c.tsx": () => import("../components/mockups/variant-c.tsx"),
  "./components/mockups/variant-d.tsx": () => import("../components/mockups/variant-d.tsx"),
  "./components/mockups/hero-variants/AuroraImmersive.tsx": () => import("../components/mockups/hero-variants/AuroraImmersive.tsx"),
  "./components/mockups/hero-variants/BrutalistEditorial.tsx": () => import("../components/mockups/hero-variants/BrutalistEditorial.tsx"),
  "./components/mockups/hero-variants/CinematicSplit.tsx": () => import("../components/mockups/hero-variants/CinematicSplit.tsx")
};
